# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Blog Title
baseurl:        ""
url:            "http://mioglob.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         이름
  url:          http://mioglob.github.io
  email:        이메일주소
  github:       깃헙닉네임
  twitter:      트위터아이디

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/mioglob/mioglob.github.io
